# Generated by Django 4.2.6 on 2023-10-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.TextField(max_length=50, verbose_name='Categoria Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(max_length=200, verbose_name='Descrpcion Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='existencias',
            field=models.IntegerField(verbose_name='Existencias Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaProduccion',
            field=models.TextField(verbose_name='FechaProducion Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fechaVencimiento',
            field=models.DateField(verbose_name='FechaVencimiento Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.TextField(max_length=50, verbose_name='Nombre Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Precio Producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='proveedor',
            field=models.TextField(max_length=100, verbose_name='Proveedor Producto'),
        ),
    ]
